version: '3.8'

services:
  air-pollution-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
      - OPENAQ_CACHE_DB=/app/data/openaq_cache.db
      # Add your API keys here or use .env file
      # - NIXTLA_API_KEY=your_key_here
      # - TELEGRAM_BOT_TOKEN=your_token_here
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: PostgreSQL database for production
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: air_pollution_db
  #     POSTGRES_USER: air_pollution
  #     POSTGRES_PASSWORD: your_password_here
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# volumes:
#   postgres_data:
